on: push
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: emulation-as-a-service/cwl-rewriter@main
        with:
          workflowPath: example_workflow.cwl
          eaasBackendUrl: https://a19b53c8-2990-43ef-8ccd-6353c370d056.test.emulation.cloud/emil
          runtimeId: ae66ff3a-a3ba-4151-ad2a-735503d1f3f0
